packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  "@feod/analyzer": 0.1.1
  "@grammyjs/types": ^5.0.0
  "@types/node": ^24
  "@types/react": ^19.3.0
  "@types/react-dom": ^19.3.0
  "@vitejs/plugin-react": ^6.1.1
  drizzle-kit: ^0.31.11
  drizzle-orm: ^0.45.3
  hono: ^4.13.0
  react: ^19.3.0
  react-dom: ^19.3.0
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  wrangler: ^4.147.0

overrides:
  vite@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"

allowBuilds:
  esbuild: true
  workerd: true
